spring.application.name=demo

# Configuracoes do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5436/crud_clientes
spring.datasource.username=postgres
spring.datasource.password=******
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration